### ISSUE TITLE
Making kami use a struct so it can be used multiple times?

### ISSUE THREAD

**Issue by timcooijmans** [guregu/kami#4]
Hi, 

Thank you for your beautiful framework. I was considering building almost exactly the same and then I found kami. 

However for my use-case it would be great if kami used a struct. So it could be instantiated multiple times and the router would be local to that instance. We could extend Kami to do this by some rewriting while allowing the current global methods to stay (by using a default struct for the global methods). 

Do you think this is a good idea?

**Comment by guregu** [comment]
Hello, thank you!
I can't merge #5 right now without breaking a few things. I am interested in this, though.
I left this feature out originally for philosophical reasons, but if people need it I am willing to add it.

First, would you mind explaining your use case a little bit? What advantage do separate muxes have over using middleware for you?

**Comment by timcooijmans** [comment]
I'm developing a system that has two http-servers. One for a public API and one for a private management API.

**Comment by guregu** [comment]
How do you separate your private and public APIs? Maybe subdomains like `admin.api.com/xyz`, instead of paths like `api.com/admin/xyz`?

**Comment by timcooijmans** [comment]
I have a micro-service approach where each server has a API that offers functional methods (this one differs per micro-service) and a API that offers management methods (these are the same per micro-server). The two run on different ports (possibly with different TLS-configs).

**Comment by guregu** [comment]
Oh, cool. I can definitely see how this would be useful for you then. Thanks.
Getting rid of `kami.Context` is a pretty big breaking change. A decent amount of code exists that relies on the globals. It would be easiest to accept this if it didn't break anything, by keeping the current global behavior as-is instead of putting it behind `kami.DefaultServer`.
One idea I had would be putting this feature in a subpackage of kami (for example: `github.com/guregu/kami/mux`) and moving the shared code (middleware stuff, etc) to an internal package. What do you think?

**Comment by timcooijmans** [comment]
I would love to keep things backwards-compatible. But I'm not sure how, the globals like `kami.Context` make it very hard to support both a struct-oriented way and a global-oriented way.

**Comment by guregu** [comment]
I have a few ideas. I will try some stuff and report back!

**Comment by guregu** [comment]
@timcooijmans How about #6? It's backwards compatible and supports the same features at the cost of some ugliness in the code.

**Comment by guregu** [comment]
I've merged #6, it's basically the same as your PR. Thanks for the input!
